// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8epa1BB6m4JwTRBLkDp3g188hC0cooGo',
    appId: '1:1070041794303:web:58cc69aaa9d688234a6eca',
    messagingSenderId: '1070041794303',
    projectId: 'streaming-manage-app',
    authDomain: 'streaming-manage-app.firebaseapp.com',
    storageBucket: 'streaming-manage-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfaEOGRnZk7CEyOqytK1QHNzQJuz4OSkY',
    appId: '1:1070041794303:android:5c252954a21d2d504a6eca',
    messagingSenderId: '1070041794303',
    projectId: 'streaming-manage-app',
    storageBucket: 'streaming-manage-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhz-aA3-RM--QkuNfgrDULn1y31z3r24c',
    appId: '1:1070041794303:ios:dfb096aea60f29754a6eca',
    messagingSenderId: '1070041794303',
    projectId: 'streaming-manage-app',
    storageBucket: 'streaming-manage-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhz-aA3-RM--QkuNfgrDULn1y31z3r24c',
    appId: '1:1070041794303:ios:dfb096aea60f29754a6eca',
    messagingSenderId: '1070041794303',
    projectId: 'streaming-manage-app',
    storageBucket: 'streaming-manage-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8epa1BB6m4JwTRBLkDp3g188hC0cooGo',
    appId: '1:1070041794303:web:e5b52a6921d7e90c4a6eca',
    messagingSenderId: '1070041794303',
    projectId: 'streaming-manage-app',
    authDomain: 'streaming-manage-app.firebaseapp.com',
    storageBucket: 'streaming-manage-app.firebasestorage.app',
  );
}
